// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYNDOCtPTG1N1po_5Q34fay5UF3gEtPH8',
    appId: '1:991585304487:web:a182ae491616025fda4082',
    messagingSenderId: '991585304487',
    projectId: 'order-app-94953',
    authDomain: 'order-app-94953.firebaseapp.com',
    databaseURL: 'https://order-app-94953-default-rtdb.firebaseio.com',
    storageBucket: 'order-app-94953.firebasestorage.app',
    measurementId: 'G-NK87N3TSMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4NBLN9b7PyjZkKSCGvY0RzCQAEKuvHs',
    appId: '1:991585304487:android:d2a0745e31f737fbda4082',
    messagingSenderId: '991585304487',
    projectId: 'order-app-94953',
    databaseURL: 'https://order-app-94953-default-rtdb.firebaseio.com',
    storageBucket: 'order-app-94953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmKc5YZQelR08lKfFB0rlXe-z3Gvcmmc',
    appId: '1:991585304487:ios:546d63628b1e0dbada4082',
    messagingSenderId: '991585304487',
    projectId: 'order-app-94953',
    databaseURL: 'https://order-app-94953-default-rtdb.firebaseio.com',
    storageBucket: 'order-app-94953.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}